### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by xeanhort** [tomazas/ATCommandTester#9]
Hi!

I've seen that the original tool has added some interesting new features, and I'm wondering if it is possible to update it :)

Thanks for this awsome tool 🙌

**Comment by tomazas** [comment]
This version was put here when the Java source was freely available on the web via Java Applet.
Since then the technologies have changed and also the tool authors have rewamped some parts of the tool to be more like a desktop app, including installer and also compiling the Java code. 

Updating now is possible but not as straightforward as before. You can use the tool in trial mode if some special functions are really necessary or hack unlimited license if you got some Java skills. If anyone wants to help with the update, then you're welcome.

**Comment by xeanhort** [comment]
Ohh, I didn't know about this movement to "close source". I'll keep using this current version as I'm not really able to help with these Java skills, and the trial version is a bit overwhelming.

Thank you!
